const data = {
    ML: [
        [
            "Automatic Removal Of Garbage Strings In OCR Text",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Automatic-Removal-Of-Garbage-Strings-In-OCR-Text.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Automatic-Removal-Of-Garbage-Strings-In-OCR-Text.ipynb",
            "https://www.kaggle.com/ritvik1909/automatic-removal-of-garbage-strings-in-ocr-text?scriptVersionId=85129988",
        ],
        [
            "Optimizing Frequency based Text Classification",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Optimizing-Frequency-based-Text-Classification.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Optimizing-Frequency-based-Text-Classification.ipynb",
            "https://www.kaggle.com/ritvik1909/optimizing-frequency-based-text-classification?scriptVersionId=82638115",
        ],
        [
            "Time Series Analysis",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Time-Series-Analysis.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Time-Series-Analysis.ipynb",
            "https://www.kaggle.com/ritvik1909/time-series-analysis?scriptVersionId=82668624",
        ],
    ],
    DL: [
        [
            "Autoencoders",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Autoencoders.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Autoencoders.ipynb",
            "https://www.kaggle.com/ritvik1909/autoencoders?scriptVersionId=82641841",
        ],
        [
            "Deep Wide And Cross Networks",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Deep-Wide-And-Cross-Networks.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Deep-Wide-And-Cross-Networks.ipynb",
            "https://www.kaggle.com/ritvik1909/deep-wide-and-cross-networks?scriptVersionId=85553799",
        ],
        [
            "Entity Embeddings",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Entity-Embeddings.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Entity-Embeddings.ipynb",
            "https://www.kaggle.com/ritvik1909/entity-embeddings?scriptVersionId=82645803",
        ],
        [
            "Knowledge Distillation",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Knowledge-Distillation.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Knowledge-Distillation.ipynb",
            "https://www.kaggle.com/ritvik1909/knowledge-distillation?scriptVersionId=82656214",
        ],
        [
            "Neural Collaborative Filtering",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Neural-Collaborative-Filtering.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Neural-Collaborative-Filtering.ipynb",
            "https://www.kaggle.com/ritvik1909/neural-collaborative-filtering?scriptVersionId=80465437",
        ],
        [
            "Normalization in Neural Networks",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Normalization-In-Neural-Networks.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Normalization-In-Neural-Networks.ipynb",
            "https://www.kaggle.com/ritvik1909/normalization-in-neural-networks?scriptVersionId=85245514",
        ],
        [
            "Time Series RNN",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Time-Series-RNN.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Time-Series-RNN.ipynb",
            "https://www.kaggle.com/ritvik1909/rnn-time-series?scriptVersionId=46943050",
        ],
    ],
    NLP: [
        [
            "Debiasing Word Vectors",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Debiasing-Word-Vectors.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Debiasing-Word-Vectors.ipynb",
            "https://www.kaggle.com/ritvik1909/debiasing-word-vectors?scriptVersionId=82639147",
        ],
        [
            "Masked Language Modelling Attention",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Masked-Language-Modelling-Attention.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Masked-Language-Modelling-Attention.ipynb",
            "https://www.kaggle.com/ritvik1909/masked-language-modelling-attention?scriptVersionId=83225207",
        ],
        [
            "Masked Language Modelling RNN",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Masked-Language-Modelling-RNN.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Masked-Language-Modelling-RNN.ipynb",
            "https://www.kaggle.com/ritvik1909/masked-language-modelling-rnn?scriptVersionId=83224388",
        ],
        [
            "Named Entity Recognition Attention",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Named-Entity-Recognition-Attention.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Named-Entity-Recognition-Attention.ipynb",
            "https://www.kaggle.com/ritvik1909/named-entity-recognition-attention?scriptVersionId=83025663",
        ],
        [
            "Named Entity Recognition Flair BiLSTM CRF",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Named-Entity-Recognition-Flair-BiLSTM-CRF.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Named-Entity-Recognition-Flair-BiLSTM-CRF.ipynb",
            "https://www.kaggle.com/ritvik1909/named-entity-recognition?scriptVersionId=70360857",
        ],
        [
            "Named Entity Recognition RNN",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Named-Entity-Recognition-RNN.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Named-Entity-Recognition-RNN.ipynb",
            "https://www.kaggle.com/ritvik1909/named-entity-recognition?scriptVersionId=69474596",
        ],
        [
            "Named Entity Recognition Spacy",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Named-Entity-Recognition-Spacy.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Named-Entity-Recognition-Spacy.ipynb",
            "https://www.kaggle.com/ritvik1909/named-entity-recognition?scriptVersionId=70205863",
        ],
        [
            "Neural Machine Translation Attention",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Neural-Machine-Translation-Attention.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Neural-Machine-Translation-Attention.ipynb",
            "https://www.kaggle.com/ritvik1909/neural-machine-translation-attention?scriptVersionId=84722622",
        ],
        [
            "Neural Machine Translation Auto Encoder",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Neural-Machine-Translation-Auto-Encoder.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Neural-Machine-Translation-Auto-Encoder.ipynb",
            "https://www.kaggle.com/ritvik1909/nmt-autoencoder-date-format-convertor?scriptVersionId=49381767",
        ],
        [
            "Neural Machine Translation Teacher Forcing",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Neural-Machine-Translation-Teacher-Forcing.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Neural-Machine-Translation-Teacher-Forcing.ipynb",
            "https://www.kaggle.com/ritvik1909/nmt-with-teacher-forcing-date-format-convertor?scriptVersionId=79242874",
        ],
        [
            "Question Answering Attention",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Question-Answering-Attention.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Question-Answering-Attention.ipynb",
            "https://www.kaggle.com/ritvik1909/question-answering-attention?scriptVersionId=84791869",
        ],
        [
            "Question Answering RNN",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Question-Answering-RNN.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Question-Answering-RNN.ipynb",
            "https://www.kaggle.com/ritvik1909/question-answering-rnn?scriptVersionId=84788718",
        ],
        [
            "Siamese Network Text Similarity",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Siamese-Network-Text-Similarity.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Siamese-Network-Text-Similarity.ipynb",
            "https://www.kaggle.com/ritvik1909/siamese-network-text-similarity?scriptVersionId=82662710",
        ],
        [
            "Text Classification Attention Positional Embeddings",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Text-Classification-Attention-Positional%20Embeddings.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Text-Classification-Attention-Positional%20Embeddings.ipynb",
            "https://www.kaggle.com/ritvik1909/text-classification-attention?scriptVersionId=82752118",
        ],
        [
            "Text Classification Attention",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Text-Classification-Attention.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Text-Classification-Attention.ipynb",
            "https://www.kaggle.com/ritvik1909/text-classification-attention?scriptVersionId=82732089",
        ],
        [
            "Text Classification RNN",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Text-Classification-RNN.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Text-Classification-RNN.ipynb",
            "https://www.kaggle.com/ritvik1909/rnn-text-classification?scriptVersionId=47068841",
        ],
        [
            "Text Generation RNN",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Text-Generation-RNN.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Text-Generation-RNN.ipynb",
            "https://www.kaggle.com/ritvik1909/rnn-text-generation?scriptVersionId=46981342",
        ],
    ],
    CV: [
        [
            "Conditional GAN",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Conditional-GAN.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Conditional-GAN.ipynb",
            "https://www.kaggle.com/ritvik1909/conditional-gan?scriptVersionId=75100045",
        ],
        [
            "Cycle GAN",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Cycle-GAN.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Cycle-GAN.ipynb",
            "https://www.kaggle.com/ritvik1909/cycle-gan?scriptVersionId=75955994",
        ],
        [
            "Deep Convolutional GAN",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Deep-Convolutional-GAN.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Deep-Convolutional-GAN.ipynb",
            "https://www.kaggle.com/ritvik1909/deep-convolutional-gan?scriptVersionId=75077938",
        ],
        [
            "Denoising Autoencoder",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Denoising-Autoencoder.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Denoising-Autoencoder.ipynb",
            "https://www.kaggle.com/ritvik1909/denoising-autoencoder-image-augmentation?scriptVersionId=48267084",
        ],
        [
            "Facial Keypoint Detection CNN",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Facial-Keypoint-Detection-CNN.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Facial-Keypoint-Detection-CNN.ipynb",
            "https://www.kaggle.com/ritvik1909/facial-keypoint-detection-cnn-aug-tl?scriptVersionId=50723092",
        ],
        [
            "Image Classification CNN Transfer Learning",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Image-Classification-CNN-Transfer-Learning.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Image-Classification-CNN-Transfer-Learning.ipynb",
            "https://www.kaggle.com/ritvik1909/dont-make-a-fruit-salad?scriptVersionId=44431755",
        ],
        [
            "Masked Autoencoder Vision Transformer",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Masked-Autoencoder-Vision-Transformer.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Masked-Autoencoder-Vision-Transformer.ipynb",
            "https://www.kaggle.com/ritvik1909/masked-autoencoder-vision-transformer?scriptVersionId=85466851",
        ],
        [
            "Image Colorization Autoencoder",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Image-Colorization-Autoencoder.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Image-Colorization-Autoencoder.ipynb",
            "https://www.kaggle.com/ritvik1909/image-colorization-autoencoder?scriptVersionId=49009402",
        ],
        [
            "Multi Label Image Classification",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Multi-Label-Image-Classification.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Multi-Label-Image-Classification.ipynb",
            "https://www.kaggle.com/ritvik1909/multi-label-image-classification?scriptVersionId=62965825",
        ],
        [
            "Neural Style Transfer",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Neural-Style-Transfer.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Neural-Style-Transfer.ipynb",
            "https://www.kaggle.com/ritvik1909/neural-style-transfer?scriptVersionId=80385147",
        ],
        [
            "Object Localization CNN",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Object-Localization-CNN.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Object-Localization-CNN.ipynb",
            "https://www.kaggle.com/ritvik1909/object-localization-cnn?scriptVersionId=59200460",
        ],
        [
            "Semantic Segmentation CNN",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Semantic-Segmentation-CNN.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Semantic-Segmentation-CNN.ipynb",
            "https://www.kaggle.com/ritvik1909/salt-identification-semantic-segmentation?scriptVersionId=52117929",
        ],
        [
            "Siamese Network",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Siamese-Network.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Siamese-Network.ipynb",
            "https://www.kaggle.com/ritvik1909/siamese-network?scriptVersionId=82657693",
        ],
        [
            "Speech Classification Spectrogram CNN",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Speech-Classification-Spectrogram-CNN.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Speech-Classification-Spectrogram-CNN.ipynb",
            "https://www.kaggle.com/ritvik1909/speech-classification-spectrogram-cnn?scriptVersionId=82640485",
        ],
        [
            "Style GAN",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Style-GAN.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Style-GAN.ipynb",
            "https://www.kaggle.com/ritvik1909/style-gan?scriptVersionId=75863297",
        ],
        [
            "Variational Auto Encoder",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Variational-Auto-Encoder.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Variational-Auto-Encoder.ipynb",
            "https://www.kaggle.com/ritvik1909/variational-auto-encoder?scriptVersionId=75599513",
        ],
        [
            "Wasserstein GAN With Gradient Penalty",
            "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Wasserstein-GAN-With-Gradient-Penalty.ipynb",
            "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Wasserstein-GAN-With-Gradient-Penalty.ipynb",
            "https://www.kaggle.com/ritvik1909/wasserstein-gan-with-gradient-penalty?scriptVersionId=75103712",
        ],
    ],
};