const data = {
  ML: [
    [
      "Automatic Removal Of Garbage Strings In OCR Text",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Automatic-Removal-Of-Garbage-Strings-In-OCR-Text.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Automatic-Removal-Of-Garbage-Strings-In-OCR-Text.ipynb",
      "https://www.kaggle.com/ritvik1909/automatic-removal-of-garbage-strings-in-ocr-text",
    ],
    [
      "Optimizing Frequency based Text Classification",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Optimizing-Frequency-based-Text-Classification.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Optimizing-Frequency-based-Text-Classification.ipynb",
      "https://www.kaggle.com/ritvik1909/optimizing-frequency-based-text-classification",
    ],
    [
      "Time Series Analysis",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Time-Series-Analysis.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Time-Series-Analysis.ipynb",
      "https://www.kaggle.com/ritvik1909/time-series-analysis",
    ],
  ],
  DL: [
    [
      "Autoencoders",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Autoencoders.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Autoencoders.ipynb",
      "https://www.kaggle.com/ritvik1909/autoencoders",
    ],
    [
      "Deep Neural Decision Forests",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Deep-Neural-Decision-Forests.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Deep-Neural-Decision-Forests.ipynb",
      "https://www.kaggle.com/ritvik1909/deep-neural-decision-forests",
    ],
    [
      "Deep Wide And Cross Networks",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Deep-Wide-And-Cross-Networks.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Deep-Wide-And-Cross-Networks.ipynb",
      "https://www.kaggle.com/ritvik1909/deep-wide-and-cross-networks",
    ],
    [
      "Entity Embeddings",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Entity-Embeddings.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Entity-Embeddings.ipynb",
      "https://www.kaggle.com/ritvik1909/entity-embeddings",
    ],
    [
      "Feature Tokenizer Transformer",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Feature-Tokenizer-Transformer.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Feature-Tokenizer-Transformer.ipynb",
      "https://www.kaggle.com/ritvik1909/feature-tokenizer-transformer",
    ],
    [
      "Knowledge Distillation",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Knowledge-Distillation.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Knowledge-Distillation.ipynb",
      "https://www.kaggle.com/ritvik1909/knowledge-distillation",
    ],
    [
      "Learning Rate Schedules",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Learning-Rate-Schedules.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Learning-Rate-Schedules.ipynb",
      "https://www.kaggle.com/ritvik1909/learning-rate-schedules",
    ],
    [
      "Neural Collaborative Filtering",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Neural-Collaborative-Filtering.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Neural-Collaborative-Filtering.ipynb",
      "https://www.kaggle.com/ritvik1909/neural-collaborative-filtering",
    ],
    [
      "Neural Oblivious Decision Ensembles",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Neural-Oblivious-Decision-Ensembles.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Neural-Oblivious-Decision-Ensembles.ipynb",
      "https://www.kaggle.com/ritvik1909/neural-oblivious-decision-ensembles",
    ],
    [
      "Normalization in Neural Networks",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Normalization-In-Neural-Networks.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Normalization-In-Neural-Networks.ipynb",
      "https://www.kaggle.com/ritvik1909/normalization-in-neural-networks",
    ],
    [
      "Tab Net",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Tab-Net.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Tab-Net.ipynb",
      "https://www.kaggle.com/ritvik1909/tab-net",
    ],
    [
      "Tab Transformer",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Tab-Transformer.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Tab-Transformer.ipynb",
      "https://www.kaggle.com/ritvik1909/tab-transformer",
    ],
    [
      "Tabular ResNet",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Tabular-Resnet.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Tabular-Resnet.ipynb",
      "https://www.kaggle.com/ritvik1909/tabular-resnet/",
    ],
    [
      "Time Series RNN",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Time-Series-RNN.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Time-Series-RNN.ipynb",
      "https://www.kaggle.com/ritvik1909/rnn-time-series",
    ],
  ],
  NLP: [
    [
      "Debiasing Word Vectors",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Debiasing-Word-Vectors.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Debiasing-Word-Vectors.ipynb",
      "https://www.kaggle.com/ritvik1909/debiasing-word-vectors",
    ],
    [
      "Masked Language Modelling Attention",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Masked-Language-Modelling-Attention.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Masked-Language-Modelling-Attention.ipynb",
      "https://www.kaggle.com/ritvik1909/masked-language-modelling-attention",
    ],
    [
      "Masked Language Modelling RNN",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Masked-Language-Modelling-RNN.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Masked-Language-Modelling-RNN.ipynb",
      "https://www.kaggle.com/ritvik1909/masked-language-modelling-rnn",
    ],
    [
      "Named Entity Recognition Attention",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Named-Entity-Recognition-Attention.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Named-Entity-Recognition-Attention.ipynb",
      "https://www.kaggle.com/ritvik1909/named-entity-recognition-attention",
    ],
    [
      "Named Entity Recognition Flair BiLSTM CRF",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Named-Entity-Recognition-Flair-BiLSTM-CRF.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Named-Entity-Recognition-Flair-BiLSTM-CRF.ipynb",
      "https://www.kaggle.com/ritvik1909/named-entity-recognition?scriptVersionId=70360857",
    ],
    [
      "Named Entity Recognition RNN",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Named-Entity-Recognition-RNN.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Named-Entity-Recognition-RNN.ipynb",
      "https://www.kaggle.com/ritvik1909/named-entity-recognition?scriptVersionId=69474596",
    ],
    [
      "Named Entity Recognition Spacy",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Named-Entity-Recognition-Spacy.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Named-Entity-Recognition-Spacy.ipynb",
      "https://www.kaggle.com/ritvik1909/named-entity-recognition?scriptVersionId=70205863",
    ],
    [
      "Neural Machine Translation Attention",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Neural-Machine-Translation-Attention.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Neural-Machine-Translation-Attention.ipynb",
      "https://www.kaggle.com/ritvik1909/neural-machine-translation-attention",
    ],
    [
      "Neural Machine Translation Auto Encoder",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Neural-Machine-Translation-Auto-Encoder.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Neural-Machine-Translation-Auto-Encoder.ipynb",
      "https://www.kaggle.com/ritvik1909/nmt-autoencoder-date-format-convertor",
    ],
    [
      "Neural Machine Translation Teacher Forcing",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Neural-Machine-Translation-Teacher-Forcing.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Neural-Machine-Translation-Teacher-Forcing.ipynb",
      "https://www.kaggle.com/ritvik1909/nmt-with-teacher-forcing-date-format-convertor",
    ],
    [
      "Question Answering Attention",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Question-Answering-Attention.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Question-Answering-Attention.ipynb",
      "https://www.kaggle.com/ritvik1909/question-answering-attention",
    ],
    [
      "Question Answering RNN",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Question-Answering-RNN.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Question-Answering-RNN.ipynb",
      "https://www.kaggle.com/ritvik1909/question-answering-rnn",
    ],
    [
      "Siamese Network Text Similarity",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Siamese-Network-Text-Similarity.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Siamese-Network-Text-Similarity.ipynb",
      "https://www.kaggle.com/ritvik1909/siamese-network-text-similarity",
    ],
    [
      "Text Classification Attention Positional Embeddings",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Text-Classification-Attention-Positional%20Embeddings.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Text-Classification-Attention-Positional%20Embeddings.ipynb",
      "https://www.kaggle.com/ritvik1909/text-classification-attention",
    ],
    [
      "Text Classification Attention",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Text-Classification-Attention.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Text-Classification-Attention.ipynb",
      "https://www.kaggle.com/ritvik1909/text-classification-attention",
    ],
    [
      "Text Classification RNN",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Text-Classification-RNN.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Text-Classification-RNN.ipynb",
      "https://www.kaggle.com/ritvik1909/rnn-text-classification",
    ],
    [
      "Text Generation RNN",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Text-Generation-RNN.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Text-Generation-RNN.ipynb",
      "https://www.kaggle.com/ritvik1909/rnn-text-generation",
    ],
  ],
  CV: [
    [
      "Conditional GAN",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Conditional-GAN.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Conditional-GAN.ipynb",
      "https://www.kaggle.com/ritvik1909/conditional-gan",
    ],
    [
      "Cycle GAN",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Cycle-GAN.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Cycle-GAN.ipynb",
      "https://www.kaggle.com/ritvik1909/cycle-gan",
    ],
    [
      "Deep Convolutional GAN",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Deep-Convolutional-GAN.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Deep-Convolutional-GAN.ipynb",
      "https://www.kaggle.com/ritvik1909/deep-convolutional-gan",
    ],
    [
      "Denoising Autoencoder",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Denoising-Autoencoder.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Denoising-Autoencoder.ipynb",
      "https://www.kaggle.com/ritvik1909/denoising-autoencoder-image-augmentation",
    ],
    [
      "Facial Keypoint Detection CNN",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Facial-Keypoint-Detection-CNN.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Facial-Keypoint-Detection-CNN.ipynb",
      "https://www.kaggle.com/ritvik1909/facial-keypoint-detection-cnn-aug-tl",
    ],
    [
      "Image Classification CNN Transfer Learning",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Image-Classification-CNN-Transfer-Learning.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Image-Classification-CNN-Transfer-Learning.ipynb",
      "https://www.kaggle.com/ritvik1909/dont-make-a-fruit-salad",
    ],
    [
      "Image Colorization Autoencoder",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Image-Colorization-Autoencoder.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Image-Colorization-Autoencoder.ipynb",
      "https://www.kaggle.com/ritvik1909/image-colorization-autoencoder",
    ],
    [
      "Masked Autoencoder Vision Transformer",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Masked-Autoencoder-Vision-Transformer.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Masked-Autoencoder-Vision-Transformer.ipynb",
      "https://www.kaggle.com/ritvik1909/masked-autoencoder-vision-transformer",
    ],
    [
      "Multi Label Image Classification",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Multi-Label-Image-Classification.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Multi-Label-Image-Classification.ipynb",
      "https://www.kaggle.com/ritvik1909/multi-label-image-classification",
    ],
    [
      "Neural Style Transfer",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Neural-Style-Transfer.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Neural-Style-Transfer.ipynb",
      "https://www.kaggle.com/ritvik1909/neural-style-transfer",
    ],
    [
      "Object Detection Selective Search",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Object-Detection-Selective-Search.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Object-Detection-Selective-Search.ipynb",
      "https://www.kaggle.com/ritvik1909/object-detection-selective-search",
    ],
    [
      "Object Detection Sliding Window",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Object-Detection-Sliding-Window.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Object-Detection-Sliding-Window.ipynb",
      "https://www.kaggle.com/ritvik1909/object-detection-sliding-window",
    ],
    [
      "Object Localization CNN",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Object-Localization-CNN.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Object-Localization-CNN.ipynb",
      "https://www.kaggle.com/ritvik1909/object-localization-cnn",
    ],
    [
      "Semantic Segmentation CNN",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Semantic-Segmentation-CNN.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Semantic-Segmentation-CNN.ipynb",
      "https://www.kaggle.com/ritvik1909/salt-identification-semantic-segmentation",
    ],
    [
      "Siamese Network",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Siamese-Network.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Siamese-Network.ipynb",
      "https://www.kaggle.com/ritvik1909/siamese-network",
    ],
    [
      "Speech Classification Spectrogram CNN",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Speech-Classification-Spectrogram-CNN.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Speech-Classification-Spectrogram-CNN.ipynb",
      "https://www.kaggle.com/ritvik1909/speech-classification-spectrogram-cnn",
    ],
    [
      "Style GAN",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Style-GAN.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Style-GAN.ipynb",
      "https://www.kaggle.com/ritvik1909/style-gan",
    ],
    [
      "Text Recognition CRNN",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Text-Recognition-CRNN.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Text-Recognition-CRNN.ipynb",
      "https://www.kaggle.com/ritvik1909/text-recognition-crnn",
    ],
    [
      "Timeline of CNNs",
      "https://www.kaggle.com/code/ritvik1909/timeline-of-cnns",
      "https://www.kaggle.com/code/ritvik1909/timeline-of-cnns",
      "https://www.kaggle.com/code/ritvik1909/timeline-of-cnns",
    ],
    [
      "Variational Auto Encoder",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Variational-Auto-Encoder.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Variational-Auto-Encoder.ipynb",
      "https://www.kaggle.com/ritvik1909/variational-auto-encoder",
    ],
    [
      "Wasserstein GAN With Gradient Penalty",
      "https://github.com/Ritvik19/Implemented-Data-Science/blob/main/Wasserstein-GAN-With-Gradient-Penalty.ipynb",
      "https://nbviewer.jupyter.org/github/Ritvik19/Implemented-Data-Science/blob/main/Wasserstein-GAN-With-Gradient-Penalty.ipynb",
      "https://www.kaggle.com/ritvik1909/wasserstein-gan-with-gradient-penalty",
    ],
  ],
};
