const autoencoders = [
  {
    title: "Auto Encoders",
    link: "https://ritvik19.medium.com/papers-explained-review-11-auto-encoders-3b8f08b4eac0#b8a0",
    date: "",
    description: "",
    tags: ["Autoencoders"],
  },
  {
    title: "Sparse Auto Encoders",
    link: "https://ritvik19.medium.com/papers-explained-review-11-auto-encoders-3b8f08b4eac0#f605",
    date: "",
    description: "",
    tags: ["Autoencoders"],
  },
  {
    title: "K Sparse Auto Encoders",
    link: "https://ritvik19.medium.com/papers-explained-review-11-auto-encoders-3b8f08b4eac0#23b0",
    date: "",
    description: "",
    tags: ["Autoencoders"],
  },
  {
    title: "Contractive Auto Encoders",
    link: "https://ritvik19.medium.com/papers-explained-review-11-auto-encoders-3b8f08b4eac0#23b3",
    date: "",
    description: "",
    tags: ["Autoencoders"],
  },
  {
    title: "Convolutional Auto Encoders",
    link: "https://ritvik19.medium.com/papers-explained-review-11-auto-encoders-3b8f08b4eac0#59a1",
    date: "",
    description: "",
    tags: ["Autoencoders"],
  },
  {
    title: "Sequence to Sequence Auto Encoders",
    link: "https://ritvik19.medium.com/papers-explained-review-11-auto-encoders-3b8f08b4eac0#73e0",
    date: "",
    description: "",
    tags: ["Autoencoders"],
  },
  {
    title: "Denoising Auto Encoders",
    link: "https://ritvik19.medium.com/papers-explained-review-11-auto-encoders-3b8f08b4eac0#1829",
    date: "",
    description: "",
    tags: ["Autoencoders"],
  },
  {
    title: "Variational Auto Encoders",
    link: "https://ritvik19.medium.com/papers-explained-review-11-auto-encoders-3b8f08b4eac0#a626",
    date: "",
    description: "",
    tags: ["Autoencoders"],
  },
  {
    title: "Masked Auto Encoders",
    link: "https://ritvik19.medium.com/papers-explained-review-11-auto-encoders-3b8f08b4eac0#2247",
    date: "",
    description: "",
    tags: ["Autoencoders"],
  },
];
